name: Reusable Package Manager Notification

on:
  workflow_call:
    inputs:
      tool_name:
        description: 'Name of the tool to update in package managers (e.g., quickctx, shelltape)'
        required: true
        type: string
      version:
        description: 'Version to update (e.g., 0.1.1). If not specified, uses the release tag.'
        required: false
        type: string
        default: ''
    secrets:
      APP_ID:
        description: 'GitHub App ID for authentication'
        required: true
      APP_PRIVATE_KEY:
        description: 'GitHub App private key for authentication'
        required: true

permissions:
  contents: read

jobs:
  notify-package-repo:
    name: Notify Package Repository
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: CaddyGlow
          repositories: homebrew-packages

      - name: Get version
        id: version
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            VERSION="${{ inputs.version }}"
          else
            VERSION="${{ github.event.release.tag_name }}"
            VERSION="${VERSION#v}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Notifying package repository of version: $VERSION"

      - name: Trigger package repository update
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/CaddyGlow/homebrew-packages/dispatches \
            -d '{
              "event_type": "update-package",
              "client_payload": {
                "tool": "${{ inputs.tool_name }}",
                "version": "${{ steps.version.outputs.VERSION }}",
                "repository": "${{ github.repository }}"
              }
            }'

      - name: Summary
        run: |
          echo "Triggered update in homebrew-packages repository"
          echo "  Tool: ${{ inputs.tool_name }}"
          echo "  Version: ${{ steps.version.outputs.VERSION }}"
          echo ""
          echo "Check workflow status at:"
          echo "https://github.com/CaddyGlow/homebrew-packages/actions"
