name: Build Debian Packages (Reusable)

on:
  workflow_call:
    inputs:
      tool:
        description: 'Tool name (e.g., quickctx)'
        required: true
        type: string
      version:
        description: 'Version without v prefix (e.g., 0.1.4)'
        required: true
        type: string
      repository:
        description: 'Repository in format owner/repo (e.g., CaddyGlow/quickctx)'
        required: true
        type: string
      release_tag:
        description: 'Release tag to upload to (default: v{version})'
        required: false
        type: string
        default: ''

permissions:
  contents: write

concurrency:
  group: "debian-build-${{ inputs.tool }}-${{ inputs.version }}"
  cancel-in-progress: false

jobs:
  build-debian:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout homebrew-packages for metadata
        uses: actions/checkout@v4
        with:
          repository: CaddyGlow/homebrew-packages
          path: homebrew-packages

      - name: Set release tag
        id: release
        run: |
          if [ -n "${{ inputs.release_tag }}" ]; then
            RELEASE_TAG="${{ inputs.release_tag }}"
          else
            RELEASE_TAG="v${{ inputs.version }}"
          fi
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_OUTPUT
          echo "Using release tag: $RELEASE_TAG"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: matrix.arch == 'arm64'

      - name: Build Debian package
        run: |
          TOOL="${{ inputs.tool }}"
          VERSION="${{ inputs.version }}"
          REPO="${{ inputs.repository }}"
          ARCH="${{ matrix.arch }}"
          RELEASE_TAG="${{ steps.release.outputs.RELEASE_TAG }}"

          echo "Building Debian package:"
          echo "  Tool: $TOOL"
          echo "  Version: $VERSION"
          echo "  Repository: $REPO"
          echo "  Architecture: $ARCH"

          # Determine platform for Docker
          if [ "$ARCH" = "arm64" ]; then
            PLATFORM="linux/arm64"
            RUST_ARCH="aarch64"
          else
            PLATFORM="linux/amd64"
            RUST_ARCH="x86_64"
          fi

          # Get description from Homebrew formula if available
          if [ -f "homebrew-packages/Formula/$TOOL.rb" ]; then
            DESCRIPTION=$(grep -oP 'desc "\K[^"]+' "homebrew-packages/Formula/$TOOL.rb" 2>/dev/null || echo "Tool from $REPO")
            BINARIES=$(grep -oP 'bin\.install "\K[^"]+' "homebrew-packages/Formula/$TOOL.rb" 2>/dev/null | sort -u || echo "$TOOL")
          else
            DESCRIPTION="Tool from $REPO"
            BINARIES="$TOOL"
          fi

          echo "Description: $DESCRIPTION"
          echo "Binaries: $BINARIES"

          # Create build script
          cat > build-deb.sh << 'BUILDSCRIPT'
          #!/bin/bash
          set -e

          TOOL=$1
          VERSION=$2
          ARCH=$3
          RUST_ARCH=$4
          REPO=$5
          DESCRIPTION=$6
          RELEASE_TAG=$7
          shift 7
          BINARIES="$@"

          echo "Building Debian package for $TOOL v$VERSION ($ARCH)"

          # Install required tools
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -qq
          apt-get install -y -qq wget tar dpkg-dev ca-certificates

          # Create package structure
          PKGDIR="${TOOL}_${VERSION}_${ARCH}"
          mkdir -p "$PKGDIR/usr/bin"
          mkdir -p "$PKGDIR/DEBIAN"

          # Download and extract the tarball from GitHub release
          DOWNLOAD_URL="https://github.com/$REPO/releases/download/${RELEASE_TAG}/${TOOL}-${RUST_ARCH}-unknown-linux-gnu.tar.gz"
          echo "Downloading from: $DOWNLOAD_URL"

          wget -q -O /tmp/package.tar.gz "$DOWNLOAD_URL"

          # Extract directly to bin directory
          tar -xzf /tmp/package.tar.gz -C "$PKGDIR/usr/bin"

          # Clean up
          rm /tmp/package.tar.gz

          # Verify binaries exist
          echo "Verifying binaries..."
          for binary in $BINARIES; do
            if [ -f "$PKGDIR/usr/bin/$binary" ]; then
              echo "  ✓ $binary"
            else
              echo "  ✗ $binary (not found)"
              exit 1
            fi
          done

          # Make binaries executable
          find "$PKGDIR/usr/bin" -type f -exec chmod 755 {} \;

          # Create control file
          cat > "$PKGDIR/DEBIAN/control" << EOF
          Package: $TOOL
          Version: $VERSION
          Section: utils
          Priority: optional
          Architecture: $ARCH
          Maintainer: CaddyGlow <caddyglow@pm.me>
          Description: $DESCRIPTION
          EOF

          # Build the .deb package
          dpkg-deb --build "$PKGDIR" "/output/${TOOL}_${VERSION}_${ARCH}.deb"

          echo "Package built: /output/${TOOL}_${VERSION}_${ARCH}.deb"
          ls -lh /output/
          BUILDSCRIPT

          chmod +x build-deb.sh

          # Create output directory
          mkdir -p output-$ARCH

          # Run build in Debian container
          docker run --rm \
            --platform $PLATFORM \
            -v "$(pwd)/build-deb.sh:/workspace/build-deb.sh" \
            -v "$(pwd)/output-$ARCH:/output" \
            debian:bookworm-slim \
            bash /workspace/build-deb.sh "$TOOL" "$VERSION" "$ARCH" "$RUST_ARCH" "$REPO" "$DESCRIPTION" "$RELEASE_TAG" $BINARIES

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debian-${{ matrix.arch }}-${{ inputs.tool }}
          path: output-${{ matrix.arch }}/*.deb

  attach-to-release:
    needs: build-debian
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: packages

      - name: List packages
        run: |
          echo "Built packages:"
          find packages -name '*.deb' -exec ls -lh {} \;

      - name: Upload to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          TOOL="${{ inputs.tool }}"
          VERSION="${{ inputs.version }}"
          REPO="${{ inputs.repository }}"
          RELEASE_TAG="${{ steps.release.outputs.RELEASE_TAG || format('v{0}', inputs.version) }}"

          echo "Uploading Debian packages to $REPO release $RELEASE_TAG"

          # Upload all .deb files to the tool's repo release
          find packages -name '*.deb' -exec gh release upload "$RELEASE_TAG" {} --repo "$REPO" --clobber \;

          echo "✅ Debian packages uploaded successfully to $REPO/releases/tag/$RELEASE_TAG"
